name: Pentest with Docker

on:
  push:
    branches:
      - main
      - test
  
  workflow_dispatch:

jobs:
  pentest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3
      
      - name: Start local server on port 8000
        run: |
          nohup python3 -m http.server 8000 > /dev/null 2>&1 &
          sleep 3

      - name: Run Kali Linux Docker Container
        run: |
          docker run --rm --privileged --network host -e DEBIAN_FRONTEND=noninteractive -v ${{ runner.temp }}/output:${{ runner.temp }}/output am2501/kalidef /bin/bash -c '
          echo "nmap↓"
          sudo nmap -sV -T4 -p 7000-9000 127.0.0.1 -oN ${{ runner.temp }}/output/nmap_report.txt -oX ${{ runner.temp }}/output/nmap_report.xml
          echo "sqlmap↓"
          sqlmap -u "http://127.0.0.1:8000/" --level=5 --risk=3 --random-agent --tamper=space2comment --output-dir=${{ runner.temp }}/output
          echo "cracking↓"
          apt update && apt install -y seclists
          hydra -l user -P /usr/share/seclists/Passwords/xato-net-10-million-passwords-10000.txt 127.0.0.1 http-post-form "/login_form:username=^USER^&password=^PASS^:F=メールアドレスもしくはパスワードが間違っています。" -s 8000 -o ${{ runner.temp }}/output/passwords.txt
          '
      
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v4
        with:
          name: vulnerability_report
          path: ${{ runner.temp }}/output/*